# Resolução exercício *dplyr* avançado

## Parte 1: Seguro Defeso e Bolsa Família

```{r}

# limpar ambiente global
rm(list = ls())

# resolução exercício dplyr avançado
# pacotes necessários
library(data.table)
library(dplyr)
library(lubridate)

# especificar diretório
setwd("C:/curso_r/dados")

# listar arquivos
list.files()

# os arquivos são mto grande, vamos ler as primeiras lihnas
bf <- fread("201501_BolsaFamiliaFolhaPagamento.csv", dec = ",", 
            nrows = 3)
str(bf)


########################## 
# baixando bolsa familia #
##########################

### DUAS FORMAS DE BAIXAR
## FORMA 1
# com read_tsv(), pois o delimitador é "\t"
bf <- read_tsv("201501_BolsaFamiliaFolhaPagamento.csv",
               locale = locale(encoding = "Latin1"))

## FORMA 2
# Cadastros do Bolsa família de Janeiro de 2015
bf <- fread("201501_BolsaFamiliaFolhaPagamento.csv", 
            dec =",")
# objeto muito grande. veja!
bf_size <- object.size(bf)
print(bf_size, units = "auto")

# queremos apenas o NIS - coluna 8
colnames(bf) 
bf<- fread("201501_BolsaFamiliaFolhaPagamento.csv", 
           dec =",", select = c(8, 11))
bf_size <- object.size(bf)
print(bf_size, units = "auto")

########################## 
# baixando seguro defeso #
##########################

# listar arquivo
list.files()

# baixar arquivo
pesc<- fread("201501_SeguroDefeso.csv", 
                dec = ",")

# ver estrutura do banco
glimpse(pesc)
# ler primeiras linhas
head(pesc)


#################
# adequar nomes #
#################

# Função para editar nomes
adequar_nomes<- function(x){
  require(stringr)
  require(stringi)
  x = stri_trans_general(x, "Latin-ASCII")
  x = tolower(x)
  x = str_replace_all(x, "[[:punct:][:space:]]", "_")
  x
}

# Adequar nomes do cadastro do Bolsa Família
colnames(bf)<- adequar_nomes(colnames(bf))
colnames(bf) <- c("nis_favorecido", "valor_parcela_pbf")

# Adequar nomes do banco Pescador Artesanal
colnames(pesc)<- adequar_nomes(colnames(pesc))


#######################
# trabalhar com datas #
#######################

## primeiro, ajeitar a data de referência
pesc$data_referencia <- paste0("01/",pesc$data_referencia)

# mas podemos fazer isso de forma automática

# vamos escolher todas as colunas que começam com datas
a <- select(pesc, contains("data")) %>% 
     colnames() 

# depois, aplicar o comando mutate_at
pesc<- pesc %>% 
  mutate_at(.vars = a, funs(dmy))

# se fizermos diretamente, termos o seguinte
#pesc <- pesc %>% 
#  mutate_at(.vars = select(pesc, contains("data")) %>% colnames, funs(dmy) )

# todas variaveis sao relevantes?
# excluir as que não interessam
pesc <- pesc %>% 
  select(-c(numero_requerimento, cpf_pescador, numero_rgp, 
            nome_municipio_pescador, codigofuncao:codigoacao))

# há linhas repetidas?
pesc <- pesc %>% 
  mutate(pis_dup = duplicated(pis_pescador))

# contar duplicados
pesc %>% summarise(unicos = n_distinct(pis_pescador), 
                   duplicados = sum(pis_dup))

# filtrar apenas casos de 2015- supondo que os casos são duplicados
# por serem de períodos diferentes
pesc <- pesc %>% 
  filter(year(data_emissao_parcela) == 2015 & month(data_emissao_parcela)== 1) %>% 
  distinct(pis_pescador, .keep_all = TRUE)


##########################################
# calcular o número de bolsas por cidade #
##########################################
## dados população - na pasta de dados do curso
library(readxl)
pop <- read_excel("pop_2015.xls", sheet = 2)
glimpse(pop)

# o código ibge tem 7 números, mas precisamos cortar 6
pop <- pop %>% 
  mutate(cod_ibge = substr(cod_ibge, 1, 6) %>% as.numeric())

# 1. qual tipo de seguro defeso tem maior número de beneficiários
pesc %>% 
  group_by(portaria_defeso_ibama) %>% 
  summarise(n_ben = n()) %>% 
  arrange(-n_ben)

# Número de pescadores em relação à população municipal
t <- pesc %>% 
  distinct(pis_pescador, .keep_all = T) %>%
  group_by(codigo_ibge_municipio_pescador) %>%
  count() %>% 
  arrange(-n)

# juntar as bases
t <- inner_join(t, pop, by = c("codigo_ibge_municipio_pescador" = "cod_ibge"))

# calcular percentual
t<- t%>% mutate(percentual = (n/pop)*100) %>% 
  arrange(-percentual)

t

# 3. Quantos indivíduos recebem bolsa família e seguro defeso no período?
# Cruzar bases de dados para descobrir quais os registros repetidos
recebem_dois<- inner_join(bf, pesc, 
                          by = c("nis_favorecido" = "pis_pescador"))

# Transformar esse banco em um tibble
glimpse(recebem_dois)

# contar quantos recebem os dois:pbf e seguro defeso
recebem_dois %>% count()

# 4. contar valores por uf
rcb_uf <- recebem_dois %>% 
  group_by(uf_pescador) %>% 
  count()
rcb_uf

# Atenção: em bases administrativas, parte dos registros podem 
# aparecer repetidos por alguma razão.
# no caso abaixo, por conta de nis repetidos no pbf
casos.repetidos <- recebem_dois %>% 
  group_by(nis_favorecido)%>% 
  count()%>%
  filter(n>1)

casos.repetidos


# Entre os casos repetidos, qual a distribuicao
casos.repetidos%>%
  group_by(n)%>%
  count()
# 5. Estime a economia de recursos que a suspensão do 
# recebimento do Bolsa Família durante o recebimento do seguro defeso 
# poderá gerar

recebem_dois %>% 
  summarise(economia_pbf = as.numeric(valor_parcela_pbf) %>% sum(na.rm = TRUE))

# 6. sumário de dados por regiao
seg_def_reg <- recebem_dois %>% 
  mutate(regiao = substr(uf_pescador, 1, 1)) %>% 
  group_by(regiao) %>% 
  summarise(n_ben = n(),
            media_ben = mean(valor_parcela))

# 7. Exporte os dados para tabelas em csv

tab1 <- recebem_dois %>% 
  group_by(uf_pescador) %>% 
  summarise(total = n(),
            valor_pago_pbf = sum(as.numeric(valor_parcela_pbf),  na.rm = TRUE),
            valor_pago_seg = sum(as.numeric(valor_parcela),  na.rm = TRUE))
write.table(tab1, "tabela1.csv", sep = ";", dec = ",",
            row.names = FALSE)

```
## Parte 2: 
Repita os procedimentos da parte 1 para os dados de 2016. Você encontrou algum caso em que quem recebe bolsa família recebe seguro defeso? Nesse caso, sua política foi exitosa?

## Parte 3: RAIS

```{r}
# na rais, o separador decimal é a vírgula. 
# por isso, não devemos especificar os decimais
rais <- data.table::fread("dados_rais.txt", dec = ",")

# adequar nomes
colnames(rais) <- adequar_nomes(colnames(rais))


# verificar estrutura dos dados
glimpse(rais)

# transformar datas

# primeiro descobrir quais variáveis tem data
a<- rais %>% 
  select(contains("data")) %>% 
  colnames()
a

rais <- rais %>% 
  mutate(data_admissao_declarada = dmy(data_admissao_declarada))


# Dados sobre qualificação e remuneração
## Quais profissões têm maior qualificação?
### para identificar, temos que cruzar os dados do cbo
cbo <- readxl::read_excel("cbo_rais.xlsx")

# cruzar o cbo com a rais
rais <- rais %>% 
  mutate(cbo_ocupacao_2002 = as.numeric(cbo_ocupacao_2002)) %>% 
  inner_join(cbo)

# dados de ocupação
esc <- readxl::read_excel("RAIS_vinculos_layout.xls", 
                  sheet = "escolaridade ou g instruçao")

colnames(esc) <- adequar_nomes(colnames(esc))

rais <- rais %>% 
  inner_join( esc, by = c("escolaridade_apos_2005"))



```
